image: dockersource.cc.cs.nctu.edu.tw/www/images/laravel-build-image:7.1-20190626
stages:
  - build for test
  - test
  - build for deploy
  - deploy

include:
  - project: 'devops/templates'
    file: 'laravel/modules/build/test(sso-sdk).gitlab-ci.yml'
  - project: 'devops/templates'
    file: 'laravel/modules/test/psr2.gitlab-ci.yml'
  - project: 'devops/templates'
    file: 'laravel/modules/test/eslint.gitlab-ci.yml'
  - project: 'devops/templates'
    file: 'laravel/modules/build/deploy(sso-sdk).gitlab-ci.yml'
  - project: 'devops/templates'
    file: 'laravel/modules/deploy/ws.gitlab-ci.yml'
